make:
	gcc -Wall -Werror -pedantic Cliente\ TCP.c -o Cliente\ TCP
	gcc -Wall -Werror -pedantic Cliente\ UDP.c -o Cliente\ UDP
clean:
	-rm -rf Cliente\ TCP
	-rm -rf Cliente\ UDP
	-rm -rf SO2-2018-TP1.pdf
	-rm -rf What\ It\ Is.mp4
run:
	./Cliente\ TCP
