make:
	gcc -Wall -Werror -pedantic Cliente\ TCP.c -o Cliente\ TCP
clean:
	-rm -rf Cliente\ TCP
	-rm -rf SO2-2018-TP1.pdf
	-rm -rf What\ It\ Is.mp4
	-rm -rf What\ It\ Is
	-rm -rf imagen.jpg
run:
	./Cliente\ TCP
