make:
	gcc -Wall -Werror -pedantic Cliente\ TCP.c -o Cliente\ TCP
	gcc -Wall -Werror -pedantic Cliente\ UDP.c -o Cliente\ UDP
clean:
	-rm -rf Cliente\ TCP
	-rm -rf Cliente\ UDP
#run:
#	./Cliente\ TCP
