make:
	gcc -Wall -Werror -pedantic Servidor_TCP.c -o Servidor_TCP
	gcc -Wall -Werror -pedantic Servidor_UDP.c -o Servidor_UDP
	gcc -Wall -Werror -pedantic Bash/Bash.c -o Bash/Bash
clean:
	-rm -rf Servidor_TCP
	-rm -rf Servidor_UDP
	-rm -rf Bash/Bash
#run:
#	./Servidor\ TCP
