make:
	gcc -Wall -Werror -pedantic Servidor\ TCP.c -o Servidor\ TCP
	gcc -Wall -Werror -pedantic Servidor\ UDP.c -o Servidor\ UDP

clean:
	-rm -rf Servidor\ TCP
	-rm -rf Servidor\ UDP
#run:
#	./Servidor\ TCP
