make:
	gcc -Wall -Werror -pedantic Servidor\ TCP.c -o Servidor\ TCP
	gcc -Wall -Werror -pedantic Servidor\ UDP.c -o Servidor\ UDP
	gcc -Wall -Werror -pedantic Bash/Bash.c -o Bash/Bash
clean:
	-rm -rf Servidor\ TCP
	-rm -rf Servidor\ UDP
	-rm -rf Bash/Bash
#run:
#	./Servidor\ TCP
